### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ashadebi** [daimus/dnms#4]
halo mas daimus,

saya coba menggunakan docker, dan menggunakan image node:12
ada eror yang terjadi, bisa bantu saya untuk check? 

/usr/src/app/node_modules/sequelize/lib/sequelize.js:281
      throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^
Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/usr/src/app/node_modules/sequelize/lib/sequelize.js:281:13)
    at Object.<anonymous> (/usr/src/app/config/database.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/model/user.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

Terima Kasih

**Comment by daimus** [comment]
halo mas @ashadebi . versi minimum node js adalah versi 14 ya
